### test-job2.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job2
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test-job2
        image: centos:8
        command: ["bash"]
        args:
          - "-c"
          - >-
            echooo 'Hello Job!' &&
            sleep 60 &&
            echo 'Completed!'
        