### config-secret.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: default
data:
  apikey: 'xxxxxxxxxxx'
  mysql.endpoint: '10.1.1.1:3306'
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  # user1, asdfasdf
  db.userid: dXNlcjE=
  db.password: YXNkZmFzZGY=