apiVersion: v1
kind: Service
metadata:
  name: nodeapp-cip
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: nodeapp-port
      port: 8081
      targetPort: 8080
  selector:
    app: nodeapp
