apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-v2
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: stepanowon/nodeapp:2.0.0
        ports:
        - containerPort: 80