apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deploy
  labels:
    app: nodeapp
  annotations:
    kubernetes.io/change-cause: "1.0.0"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: stepanowon/nodeapp:1.0.0
        ports:
        - containerPort: 80
